ci:
  autofix_prs: false

repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.1
  hooks:
    - id: pyupgrade
      args: [ "--py38-plus" ]
- repo: https://github.com/adamchainz/django-upgrade
  rev: '1.16.0'
  hooks:
    - id: django-upgrade
      args: [ --target-version, "4.2" ]
