# Generated by Django 5.0.4 on 2026-08-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_form_builder", "0007_captcha"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionQuota",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "Submission quota",
                "verbose_name_plural": "Submission quotas",
            },
        ),
    ]
