# Generated by Django 5.2.17 on 2026-09-15 14:43

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models

import djangocms_form_builder.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_form_builder", "0009_rename_form_formplugin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_name",
                    models.SlugField(
                        help_text="Slug that uniquely identifies this form. Form submissions are filed under this name, so changing it separates new submissions from the ones collected so far.",
                        max_length=256,
                        unique=True,
                        verbose_name="Form identifier",
                    ),
                ),
                (
                    "creation_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("editor", "in the form editor"),
                            ("conversion", "converted from a form plugin"),
                        ],
                        default="editor",
                        max_length=20,
                        verbose_name="Creation method",
                    ),
                ),
            ],
            options={
                "verbose_name": "form",
                "verbose_name_plural": "forms",
                "ordering": ["form_name"],
            },
        ),
        migrations.AddField(
            model_name="formplugin",
            name="form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cms_plugins",
                to="djangocms_form_builder.form",
                verbose_name="Form",
            ),
        ),
        migrations.CreateModel(
            name="FormContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shown to editors when they pick a form. Not shown to users.",
                        max_length=256,
                        verbose_name="Name",
                    ),
                ),
                (
                    "form_login_required",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="To avoid issues with user experience use this type of form only on pages, which require login.",
                        verbose_name="Login required to submit form",
                    ),
                ),
                (
                    "form_unique",
                    models.BooleanField(
                        default=False,
                        help_text='Requires "Login required" to be checked to work.',
                        verbose_name="User can reopen form",
                    ),
                ),
                (
                    "form_floating_labels",
                    models.BooleanField(default=False, verbose_name="Floating labels"),
                ),
                (
                    "form_spacing",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Margin between fields"
                    ),
                ),
                (
                    "form_actions",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        verbose_name="Actions to be taken after form submission",
                    ),
                ),
                (
                    "action_parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "attributes",
                    djangocms_form_builder.fields.AttributesField(
                        blank=True, default=dict, verbose_name="Attributes"
                    ),
                ),
                (
                    "captcha_widget",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Read more in the <a href="https://developers.google.com/recaptcha" target="_blank">documentation</a>.',
                        max_length=16,
                        verbose_name="captcha widget",
                    ),
                ),
                (
                    "captcha_requirement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.5,
                        help_text="Only for reCaptcha v3: Minimum score required to accept challenge.",
                        max_digits=3,
                        null=True,
                        verbose_name="Minimum score requirement",
                    ),
                ),
                (
                    "captcha_config",
                    djangocms_form_builder.fields.AttributesField(
                        blank=True,
                        default=dict,
                        verbose_name="Recaptcha configuration parameters",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="djangocms_form_builder.form",
                        verbose_name="Form",
                    ),
                ),
            ],
            options={
                "verbose_name": "form content",
                "verbose_name_plural": "form contents",
            },
        ),
    ]
