name: CodeCov

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13"]  # latest release minus two
        requirements-file: [
            dj42_cms311.txt,
            dj42_cms41.txt,
            dj50_cms41.txt,
            dj51_cms41.txt,
            dj52_cms41.txt,
            dj52_cms50.txt,
        ]
        os: [
            ubuntu-latest,
        ]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '2'

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r tests/requirements/${{ matrix.requirements-file }}
        python -m pip install -e .
    - name: Generate Report
      run: |
        coverage run ./run_tests.py
    - name: Generate XML report
      run: |
        coverage xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}