name: CodeCov

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13"]  # latest release minus two
        requirements-file: [
            dj42_cms311.txt,
            dj42_cms41.txt,
            dj50_cms41.txt,
            dj51_cms41.txt,
            dj52_cms41.txt,
            dj52_cms50.txt,
        ]
        os: [
            ubuntu-latest,
        ]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '2'

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Generate Report
      run: |
        pip install -r tests/requirements/${{ matrix.requirements-file }}
        pip install -e .
        coverage run ./run_tests.py
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3

