name: Lint

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ruff check
        uses: astral-sh/ruff-action@v3
        with:
          version: latest
          args: check .
      - name: Ruff format (check only)
        uses: astral-sh/ruff-action@v3
        with:
          version: latest
          args: format --check
