name: Publish Python 🐍 distributions 📦 to TestPyPI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Install twine
      run: python -m pip install --upgrade twine
    - name: Publish distribution 📦 to Test PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: >-
        python -m twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing dist/*
